name: Godot Builder

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Builder:
    runs-on: ubuntu-latest
    container:
      image: registry.gitlab.com/greenfox/godot-build-automation:latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Project
      run: |
        builder
        cd public/web && mv breakot.html index.html
    - name: itchio-windows
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: windows
        ITCH_GAME: breakot
        ITCH_USER: cristiadu
        PACKAGE: public/breakot_windows_.zip
    - name: itchio-linux
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: linux
        ITCH_GAME: breakot
        ITCH_USER: cristiadu
        PACKAGE: public/breakot_linux_.zip
    - name: itchio-mac
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: mac
        ITCH_GAME: breakot
        ITCH_USER: cristiadu
        PACKAGE: public/breakot_mac_.zip
    - name: itchio-web
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: html5
        ITCH_GAME: breakot
        ITCH_USER: cristiadu
        PACKAGE: public/web
