name: Godot Builder

on:
  push:
    branches: [ main ]
env:
  GODOT_VERSION: 4.0.3
  PROJECT_NAME: breakot
jobs:
  windows-builder:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.0.3
    steps:
    - uses: actions/checkout@v2
    - name: build-windows
      run: |
        godot -v -e --quit --headless
        mkdir -v -p build/windows
        godot -v --export-release --headless "Windows Desktop" build/windows/$PROJECT_NAME.exe
    - name: itchio-windows
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: windows
        ITCH_GAME: ${{ env.PROJECT_NAME }}
        ITCH_USER: cristiadu
        PACKAGE: build/windows/${{ env.PROJECT_NAME }}.exe
  linux-builder:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.0.3
    steps:
    - uses: actions/checkout@v2
    - name: build-linux
      run: |
        godot -v -e --quit --headless
        mkdir -v -p build/linux
        godot -v --export-release --headless "Linux/X11" build/linux/$PROJECT_NAME.x86_64
    - name: itchio-linux
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: linux
        ITCH_GAME: ${{ env.PROJECT_NAME }}
        ITCH_USER: cristiadu
        PACKAGE: build/linux/${{ env.PROJECT_NAME }}.x86_64
  macos-builder:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.0.3
    steps:
    - uses: actions/checkout@v2
    - name: build-linux
      run: |
        godot -v -e --quit --headless
        mkdir -v -p build/mac
        godot -v --export-release --headless "Mac OSX" build/mac/$PROJECT_NAME.zip
    - name: itchio-mac
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: mac
        ITCH_GAME: ${{ env.PROJECT_NAME }}
        ITCH_USER: cristiadu
        PACKAGE: build/mac/${{ env.PROJECT_NAME }}.zip
  web-builder:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.0.3
    steps:
    - uses: actions/checkout@v2
    - name: build-linux
      run: |
        godot -v -e --quit --headless
        mkdir -v -p build/web
        godot -v --export-release --headless "HTML5" build/web/index.html
    - name: itchio-web
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: html5
        ITCH_GAME: ${{ env.PROJECT_NAME }}
        ITCH_USER: cristiadu
        PACKAGE: build/web
