name: Godot Builder

on:
  push:
    branches: [ main ]
env:
  GODOT_VERSION: 4.0.3
  PROJECT_NAME: breakot
jobs:
  builder:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.0.3
    steps:
    - uses: actions/checkout@v2
    - name: Build Project
      run: |
        mkdir -v -p ~/.local/share/godot/templates
        mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
        mkdir -v -p build
        godot --headless --verbose --export "Windows Desktop" build/${PROJECT_NAME}_windows.exe
        godot --headless --verbose --export-release "Linux/X11" build/${PROJECT_NAME}_linux.x86_64
        godot --headless --verbose --export-release "Mac OSX" build/${PROJECT_NAME}_mac.zip
        godot --headless --verbose --export-release "HTML5" build/web/index.html
    - name: itchio-windows
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: windows
        ITCH_GAME: ${{ env.PROJECT_NAME }}
        ITCH_USER: cristiadu
        PACKAGE: build/${{ env.PROJECT_NAME }}_windows.exe
    - name: itchio-linux
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: linux
        ITCH_GAME: ${{ env.PROJECT_NAME }}
        ITCH_USER: cristiadu
        PACKAGE: build/${{ env.PROJECT_NAME }}_linux.x86_64
    - name: itchio-mac
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: mac
        ITCH_GAME: ${{ env.PROJECT_NAME }}
        ITCH_USER: cristiadu
        PACKAGE: build/${{ env.PROJECT_NAME }}_mac.zip
    - name: itchio-web
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: html5
        ITCH_GAME: ${{ env.PROJECT_NAME }}
        ITCH_USER: cristiadu
        PACKAGE: build/web
