name: Godot Builder

on:
  push:
    branches: [ main ]
env:
  GODOT_VERSION: 4.0.3
  PROJECT_NAME: breakot
jobs:
  builder:
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:${{ GODOT_VERSION }}
    steps:
    - uses: actions/checkout@v2
    - name: Build Project
      run: |
        mkdir -v -p ~/.local/share/godot/templates
        mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
        mkdir -v -p build
        godot -v --export "Windows Desktop" build/${PROJECT_NAME}_windows.zip
        godot -v --export "Linux/X11" build/${PROJECT_NAME}_linux.zip
        godot -v --export "Mac OSX" ../build/${PROJECT_NAME}_mac.zip
        godot -v --export "HTML5" build/web/index.html
    - name: itchio-windows
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: windows
        ITCH_GAME: ${{ PROJECT_NAME }}
        ITCH_USER: cristiadu
        PACKAGE: build/${{ PROJECT_NAME }}_${{ CHANNEL }}.zip
    - name: itchio-linux
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: linux
        ITCH_GAME: ${{ PROJECT_NAME }}
        ITCH_USER: cristiadu
        PACKAGE: build/${{ PROJECT_NAME }}_${{ CHANNEL }}.zip
    - name: itchio-mac
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: mac
        ITCH_GAME: ${{ PROJECT_NAME }}
        ITCH_USER: cristiadu
        PACKAGE: build/${{ PROJECT_NAME }}_${{ CHANNEL }}.zip
    - name: itchio-web
      uses: manleydev/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
        CHANNEL: html5
        ITCH_GAME: ${{ PROJECT_NAME }}
        ITCH_USER: cristiadu
        PACKAGE: build/web
